import { readJson } from 'fs-extra';
import { compile } from 'json-schema-to-typescript';
import { FileInfo } from './interface';
import style from './prettierOption';

export default async function compileSchemaToCode({
  absolutePath,
  interfaceName
}: FileInfo) {
  const schema = await readJson(absolutePath);
  // disable eslint and show some user-friendly comments
  const bannerComment =
    '/* eslint:disable */\n/**\n* This file was automatically generated by json-schema-to-interface.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n* and run json-schema-to-interface to regenerate this file.\n*/';
  // set additionalProperties default to false to avoid `[k:string]: any`
  return compile(
    { ...schema, additionalProperties: schema.additionalProperties ?? false },
    interfaceName,
    { bannerComment, style }
  );
}
