name: test

on:
  push:
    branches:
      - master

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1.1.0
      - name: node dependencies cache
        uses: actions/cache@v1.1.0
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-modules-cache-${{ hashFiles('yarn.lock') }}
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install -g yarn
          yarn
      - name: build
        run: yarn test
